### ISSUE TITLE
关于 Dijkstra 算法

### ISSUE THREAD

**Issue by FrazierLei** [richenyunqi/CCF-CSP-and-PAT-solution#5]
请问 `Dijkstra` 算法中这句代码有什么作用呢？我试了下去掉也能通过。
```cpp
if (dis[p[1]] != p[0])
    continue;
```
谢谢🙏

**Comment by richenyunqi** [comment]
一个结点的dis值会不断更新，期间这个结点和它的dis值会入队多次，`if (dis[p[1]] != p[0])continue`可以保证在dis值不是最小的时候，不参与计算，减少计算量

**Comment by FrazierLei** [comment]
谢谢！
