### ISSUE TITLE
两处勘误

### ISSUE THREAD

**Issue by FrazierLei** [richenyunqi/CCF-CSP-and-PAT-solution#6]
1. P428，定义top的时候应该定义成空vector，书上定义成`vector<gg> top(MAX)`了
2. P436，dijkstra代码中`If(dis[p[0] != p[1])`，0和1写反了
3. P371，最下面ggright少了个空格

**Comment by richenyunqi** [comment]
[书籍勘误](https://github.com/richenyunqi/CCF-CSP-and-PAT-solution/blob/master/%E4%B9%A6%E7%B1%8D%E5%8B%98%E8%AF%AF.md)已更新，感谢指正！
