### ISSUE TITLE
CSP 202012-2期末阈值预测   gg t = p0 + mi - p1; 为什么t是这个计算公式？

### ISSUE THREAD

**Issue by Vitual-L** [richenyunqi/CCF-CSP-and-PAT-solution#7]

**Comment by richenyunqi** [comment]
不好意思，先前的解释有点问题，目前已更新。

>我们可以定义变量`p0`表示小于$y_i$且$result_i==0$的同学个数；定义变量`p1`表示小于$y_i$且$result_i==1$的同学个数，那么$\theta$恰好为$y_i$时的预测正确的次数就是$p0+m-p1$

一共m位同学，那么大于等于$y_i$且$result_i==1$的同学个数就是$m-p1$，那么$\theta$恰好为$y_i$时的预测正确的次数就是$p0+m-p1$
